# Generated by Django 5.1.7 on 2025-05-04 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Averiguacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('Remoção', 'Remoção'), ('Seletiva', 'Seletiva'), ('Varrição', 'Varrição')], default='Remoção', max_length=15)),
                ('pa_da_averiguacao', models.CharField(choices=[('PA1', 'PA1'), ('PA2', 'PA2'), ('PA3', 'PA3'), ('PA4', 'PA4')], default='PA1', max_length=7)),
                ('data', models.DateField(default=datetime.date(2025, 1, 1))),
                ('hora_averiguacao', models.TimeField()),
                ('rota_averiguacao', models.CharField(choices=[('ABCD001', 'ABCD001'), ('IJKL006', 'IJKL006'), ('QRST011', 'QRST011')], max_length=15)),
                ('imagem1', models.ImageField(upload_to='averiguacoes/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='averiguacoes/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='averiguacoes/')),
                ('imagem4', models.ImageField(upload_to='averiguacoes/')),
                ('imagem5', models.ImageField(blank=True, null=True, upload_to='averiguacoes/')),
                ('imagem6', models.ImageField(blank=True, null=True, upload_to='averiguacoes/')),
                ('imagem7', models.ImageField(blank=True, null=True, upload_to='averiguacoes/')),
                ('averiguador', models.CharField(max_length=15)),
            ],
        ),
    ]
