# Generated by Django 5.1.7 on 2025-05-06 16:55

import apps.averiguacao.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averiguacao', '0001_initial'),
        ('soltura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averiguacao',
            name='pa_da_averiguacao',
        ),
        migrations.RemoveField(
            model_name='averiguacao',
            name='rota_averiguacao',
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='garagem',
            field=models.CharField(default='PA1', max_length=50),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='rota',
            field=models.CharField(default='AN21', max_length=50),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='soltura_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'status_frota': 'Em Andamento'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='averiguacoes', to='soltura.soltura'),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='tipo_coleta',
            field=models.CharField(default='Remoção', max_length=50),
        ),
        migrations.AlterField(
            model_name='averiguacao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='averiguacao',
            name='hora_averiguacao',
            field=models.TimeField(default=apps.averiguacao.models.get_default_hora_averiguacao),
        ),
        migrations.AlterField(
            model_name='averiguacao',
            name='tipo_servico',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='averiguacao',
            index=models.Index(fields=['data', 'tipo_servico'], name='averiguacao_data_20bc65_idx'),
        ),
        migrations.AddIndex(
            model_name='averiguacao',
            index=models.Index(fields=['averiguador', 'data'], name='averiguacao_averigu_3ca6dc_idx'),
        ),
    ]
