# Generated by Django 5.1.7 on 2025-05-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('averiguacao', '0002_remove_averiguacao_pa_da_averiguacao_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='averiguacao',
            name='averiguacao_data_20bc65_idx',
        ),
        migrations.RemoveIndex(
            model_name='averiguacao',
            name='averiguacao_averigu_3ca6dc_idx',
        ),
    ]
