# Generated by Django 5.1.7 on 2025-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averiguacao', '0003_remove_averiguacao_averiguacao_data_20bc65_idx_and_more'),
        ('soltura', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='averiguacao',
            index=models.Index(fields=['data', 'tipo_servico'], name='averiguacao_data_20bc65_idx'),
        ),
        migrations.AddIndex(
            model_name='averiguacao',
            index=models.Index(fields=['averiguador', 'data'], name='averiguacao_averigu_3ca6dc_idx'),
        ),
    ]
