# Generated by Django 5.1.7 on 2025-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averiguacao', '0005_alter_averiguacao_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averiguacao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
