# Generated by Django 5.1.7 on 2025-05-12 14:25

import apps.averiguacao.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averiguacao', '0006_alter_averiguacao_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averiguacao',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='acoes_corretivas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='altura_fios',
            field=models.CharField(choices=[('adequada', 'Adequada'), ('inadequada', 'Inadequada')], default='adequada', max_length=15),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='caminhao_usado',
            field=models.CharField(choices=[('trucado', 'Trucado'), ('toco', 'Toco')], default='toco', max_length=10),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='coleta_com_puxada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='documentacao_veiculo',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não conforme')], default='conforme', max_length=20),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='equipamento_protecao',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não conforme')], default='conforme', max_length=20),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='hora_encerramento',
            field=models.TimeField(default=apps.averiguacao.models.get_default_hora_averiguacao),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='hora_extras',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='hora_inicio',
            field=models.TimeField(default=apps.averiguacao.models.get_default_hora_averiguacao),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='horas_improdutivas',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='inconformidades',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='largura_rua',
            field=models.CharField(choices=[('adequada', 'Adequada'), ('inadequada', 'Inadequada')], default='adequada', max_length=15),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='observacoes_operacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='puxada_adequada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='quantidade_coletores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='quantidade_viagens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='uniforme_completo',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não conforme')], default='conforme', max_length=20),
        ),
        migrations.AddField(
            model_name='averiguacao',
            name='velocidade_coleta',
            field=models.CharField(choices=[('adequada', 'Adequada'), ('media', 'Média'), ('baixa', 'Baixa')], default='adequada', max_length=10),
        ),
    ]
