# Generated by Django 5.1.7 on 2025-05-13 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averiguacao', '0007_remove_averiguacao_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averiguacao',
            name='hora_extras',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='averiguacao',
            name='horas_improdutivas',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
