# Generated by Django 5.1.7 on 2025-04-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soltura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrega_chave', models.DateTimeField(blank=True, null=True)),
                ('hora_saida_frota', models.DateTimeField(blank=True, null=True)),
                ('frequencia', models.CharField(choices=[('Diária', 'Diária'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], default='Diária', max_length=50)),
                ('setores', models.CharField(max_length=55)),
                ('celular', models.CharField(max_length=20)),
                ('lider', models.CharField(max_length=55)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('tipo_coleta', models.CharField(choices=[('Seletiva', 'Seletiva'), ('Coletiva', 'Coletiva'), ('Cata Treco', 'Cata Treco'), ('Varrição', 'Varrição')], max_length=10)),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=10)),
                ('coletores', models.ManyToManyField(limit_choices_to={'funcao': 'Coletor', 'status': 'ATIVO'}, related_name='solturas_coletor', to='colaborador.colaborador')),
                ('motorista', models.ForeignKey(limit_choices_to={'funcao': 'Motorista', 'status': 'ATIVO'}, on_delete=django.db.models.deletion.CASCADE, related_name='solturas_motorista', to='colaborador.colaborador')),
                ('veiculo', models.ForeignKey(limit_choices_to={'status': 'ATIVO'}, on_delete=django.db.models.deletion.CASCADE, related_name='solturas', to='veiculos.veiculo')),
            ],
        ),
    ]
