# Generated by Django 5.1.7 on 2025-05-04 05:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soltura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrega_chave', models.TimeField(default=datetime.time(8, 0))),
                ('hora_saida_frota', models.TimeField(default=datetime.time(8, 10))),
                ('frequencia', models.CharField(choices=[('Diária', 'Diária'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], default='Diária', max_length=50)),
                ('rota', models.CharField(default='AND1', max_length=10, null=True)),
                ('garagem', models.CharField(choices=[('PA1', 'PA1'), ('PA2', 'PA2'), ('PA3', 'PA3'), ('PA4', 'PA4')], default=' PA1', max_length=10)),
                ('setores', models.CharField(max_length=55)),
                ('celular', models.CharField(max_length=20)),
                ('lider', models.CharField(max_length=55)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('tipo_coleta', models.CharField(choices=[('Seletiva', 'Seletiva'), ('Coleta', 'Coleta'), ('Cata Treco', 'Cata Treco'), ('Varrição', 'Varrição')], max_length=10)),
                ('tipo_servico', models.CharField(choices=[('Seletiva', 'Seletiva'), ('Coleta', 'Coleta'), ('Remoção', 'Remoção'), ('Varrição', 'Varrição')], default='Seletiva', max_length=10)),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=10)),
                ('tipo_equipe', models.CharField(choices=[('Equipe1(Matutino)', 'Equipe1(Matutino)'), ('Equipe2(Vespertino)', 'Equipe2(Vespertino)'), ('Equipe3(Noturno)', 'Equipe3(Noturno)')], default='Equipe1(Matutino)', max_length=20)),
                ('data', models.DateField(default=datetime.date(2025, 1, 1))),
                ('hora_chegada', models.TimeField(default=datetime.time(14, 14), null=True)),
                ('status_frota', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Finalizada', 'Finalizada')], default='Finalizado', max_length=14, null=True)),
                ('tipo_veiculo_selecionado', models.CharField(choices=[('Baú', 'Baú'), ('Baculante', 'Basculante'), ('Seletolix', 'Seletolix')], default='Basculante', max_length=14, null=True)),
                ('bairro', models.CharField(default='Guanabara', max_length=100, null=True)),
                ('coletores', models.ManyToManyField(limit_choices_to={'funcao': 'Coletor', 'status': 'ATIVO'}, related_name='solturas_coletor', to='colaborador.colaborador')),
                ('motorista', models.ForeignKey(limit_choices_to={'funcao': 'Motorista', 'status': 'ATIVO'}, on_delete=django.db.models.deletion.CASCADE, related_name='solturas_motorista', to='colaborador.colaborador')),
                ('veiculo', models.ForeignKey(limit_choices_to={'status': 'ATIVO'}, on_delete=django.db.models.deletion.CASCADE, related_name='solturas', to='veiculos.veiculo')),
            ],
        ),
    ]
