# Generated by Django 5.1.7 on 2025-05-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='tipo_servico',
            field=models.CharField(choices=[('Seletiva', 'Seletiva'), ('Coleta', 'Coleta'), ('Remoção', 'Remoção'), ('Varrição', 'Varrição'), ('Rsu', 'Rsu')], default='Seletiva', max_length=10),
        ),
    ]
