# Generated by Django 5.1.7 on 2025-04-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soltura',
            name='tipo_equipe',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], default='Equipe1(Matutino)', max_length=10),
        ),
        migrations.AddField(
            model_name='soltura',
            name='tipo_servico',
            field=models.CharField(choices=[('Seletiva', 'Seletiva'), ('Coleta', 'Coleta'), ('Remoção', 'Remoção'), ('Varrição', 'Varrição')], default='Coleta', max_length=10),
        ),
    ]
