# Generated by Django 5.1.7 on 2025-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0002_soltura_tipo_equipe_soltura_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='tipo_servico',
            field=models.CharField(choices=[('Seletiva', 'Seletiva'), ('Coleta', 'Coleta'), ('Remoção', 'Remoção'), ('Varrição', 'Varrição')], default='Seletiva', max_length=10),
        ),
    ]
