# Generated by Django 5.1.7 on 2025-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0002_alter_soltura_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='tipo_equipe',
            field=models.CharField(choices=[('Equipe1(Matutino)', 'Equipe1(Matutino)'), ('Equipe2(Vespertino)', 'Equipe2(Vespertino)'), ('Equipe3(Noturno)', 'Equipe3(Noturno)'), ('Euipe(Diurno)', 'Euipe(Diurno)'), ('Equipe(Noturno)', 'Equipe(Noturno)')], default='Equipe1(Matutino)', max_length=20),
        ),
    ]
