# Generated by Django 5.1.7 on 2025-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0003_alter_soltura_tipo_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Diurno', 'Diurno')], max_length=10),
        ),
    ]
