# Generated by Django 5.1.7 on 2025-04-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0003_alter_soltura_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='tipo_equipe',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], default='Equipe1(Matutino)', max_length=20),
        ),
    ]
