# Generated by Django 5.1.7 on 2025-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
        ('soltura', '0004_alter_soltura_turno'),
        ('veiculos', '0002_alter_veiculo_tipo_servico_usuario_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soltura',
            index=models.Index(fields=['tipo_servico'], name='soltura_sol_tipo_se_810bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='soltura',
            index=models.Index(fields=['data'], name='soltura_sol_data_c4b404_idx'),
        ),
    ]
