# Generated by Django 5.1.7 on 2025-04-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0005_alter_soltura_tipo_equipe_alter_soltura_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='soltura',
            name='garagem',
            field=models.CharField(default='Equipe1(Matutino)', max_length=10),
        ),
        migrations.AddField(
            model_name='soltura',
            name='rota',
            field=models.CharField(default='PA1', max_length=10),
        ),
        migrations.AlterField(
            model_name='soltura',
            name='tipo_equipe',
            field=models.CharField(choices=[('Equipe1(Matutino)', 'Equipe1(Matutino)'), ('Equipe2(Vespertino)', 'Equipe2(Vespertino)'), ('Equipe3(Noturno)', 'Equipe3(Noturno)')], default='Equipe1(Matutino)', max_length=20),
        ),
    ]
