# Generated by Django 5.1.7 on 2025-05-27 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('soltura', '0005_soltura_soltura_sol_tipo_se_810bc0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soltura',
            name='equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.equipamento'),
        ),
    ]
