# Generated by Django 5.1.7 on 2025-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
        ('equipamentos', '0001_initial'),
        ('soltura', '0006_soltura_equipamento'),
        ('veiculos', '0002_alter_veiculo_tipo_servico_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='soltura',
            name='soltura_sol_tipo_se_810bc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='soltura',
            name='soltura_sol_data_c4b404_idx',
        ),
        migrations.AddIndex(
            model_name='soltura',
            index=models.Index(fields=['data', 'tipo_servico'], name='soltura_sol_data_f21a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='soltura',
            index=models.Index(fields=['data', 'tipo_equipe'], name='soltura_sol_data_7a5729_idx'),
        ),
        migrations.AddIndex(
            model_name='soltura',
            index=models.Index(fields=['garagem'], name='soltura_sol_garagem_49cf23_idx'),
        ),
        migrations.AddIndex(
            model_name='soltura',
            index=models.Index(fields=['motorista'], name='soltura_sol_motoris_9dbc68_idx'),
        ),
    ]
