# Generated by Django 5.1.7 on 2025-04-14 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0006_soltura_garagem_soltura_rota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soltura',
            name='data',
            field=models.DateField(default=datetime.date(2002, 1, 1)),
        ),
    ]
