# Generated by Django 5.1.7 on 2025-04-15 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0007_soltura_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='soltura',
            name='hora_chegada',
            field=models.TimeField(default=datetime.time(14, 14)),
        ),
        migrations.AlterField(
            model_name='soltura',
            name='hora_entrega_chave',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='soltura',
            name='hora_saida_frota',
            field=models.TimeField(default=datetime.time(8, 10)),
        ),
    ]
