# Generated by Django 5.1.7 on 2025-04-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0008_soltura_hora_chegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='tipo_coleta',
            field=models.CharField(choices=[('Seletiva', 'Seletiva'), ('Coleta', 'Coleta'), ('Cata Treco', 'Cata Treco'), ('Varrição', 'Varrição')], max_length=10),
        ),
    ]
