# Generated by Django 5.1.7 on 2025-04-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0009_alter_soltura_tipo_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='rota',
            field=models.CharField(default='PA1', max_length=10, null=True),
        ),
    ]
