# Generated by Django 5.1.7 on 2025-04-16 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0011_alter_soltura_hora_chegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='data',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
