# Generated by Django 5.1.7 on 2025-04-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0012_alter_soltura_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='soltura',
            name='status_frota',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Finalizada', 'Finalizada')], default='Finalizado', max_length=14, null=True),
        ),
    ]
