# Generated by Django 5.1.7 on 2025-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0013_soltura_status_frota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soltura',
            name='garagem',
            field=models.CharField(choices=[('PA1', 'PA1'), ('PA2', 'PA2'), ('PA3', 'PA3'), ('PA4', 'PA4')], default=' PA1', max_length=10),
        ),
        migrations.AlterField(
            model_name='soltura',
            name='rota',
            field=models.CharField(default='AND1', max_length=10, null=True),
        ),
    ]
