# Generated by Django 5.1.7 on 2025-04-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0014_alter_soltura_garagem_alter_soltura_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='soltura',
            name='tipo_veiculo_selecionado',
            field=models.CharField(choices=[('Baú', 'Baú'), ('Baculante', 'Basculante'), ('Seletolix', 'Seletolix')], default='Basculante', max_length=14, null=True),
        ),
    ]
