# Generated by Django 5.1.7 on 2025-05-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soltura', '0015_soltura_tipo_veiculo_selecionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='soltura',
            name='bairro',
            field=models.CharField(default='Guanabara', max_length=100, null=True),
        ),
    ]
