# Generated by Django 5.1.7 on 2025-05-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.IntegerField(unique=True)),
                ('funcao', models.CharField(choices=[('Motorista', 'Motorista'), ('Operador', 'Operador'), ('Coletor', 'Coletor')], max_length=9)),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Noturno', 'Noturno'), ('Vespertino', 'Vespertino')], max_length=10)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7)),
                ('pa', models.CharField(choices=[('PA1', 'PA1'), ('PA2', 'PA2'), ('PA3', 'PA3'), ('PA4', 'PA4')], max_length=4)),
            ],
            options={
                'db_table': 'colaborador',
                'indexes': [models.Index(fields=['nome'], name='colaborador_nome_ab3ec6_idx'), models.Index(fields=['matricula'], name='colaborador_matricu_23ec80_idx'), models.Index(fields=['funcao'], name='colaborador_funcao_6740bc_idx'), models.Index(fields=['pa'], name='colaborador_pa_ac17c9_idx'), models.Index(fields=['turno'], name='colaborador_turno_2f788b_idx')],
            },
        ),
    ]
