# Generated by Django 5.1.7 on 2025-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo_servico_veiculo',
            field=models.CharField(choices=[('Remoção', 'Remoção'), ('Seletiva', 'Seletiva'), ('Testes', 'Teste')], default='Remoção', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='custo_manutencao',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Custo da Manutenção'),
        ),
    ]
