# Generated by Django 5.1.7 on 2025-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_tipo_servico_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo_servico_usuario',
            field=models.CharField(blank=True, choices=[('Remoção', 'Remoção'), ('Seletiva', 'Seletiva'), ('Testes', 'Teste')], max_length=20, null=True, verbose_name='Tipo de Serviço Selecionado pelo Usuário'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_servico_veiculo',
            field=models.CharField(choices=[('Remoção', 'Remoção'), ('Seletiva', 'Seletiva'), ('Testes', 'Teste')], default='Teste', max_length=20),
        ),
    ]
