"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import sys
import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
from celery.schedules import crontab



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9offtn68!713vtcxk$fg!w4_7vw+_^2@q$*yt1(j5cydl=!pet'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.equipamentos',
    'apps.averiguacao',
    'apps.cadastro',
    'apps.captcha',
    'apps.colaborador',
    'apps.login',
    'apps.soltura',
    'apps.veiculos',
    'apps.general_recourses_wpp',
    "corsheaders"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

CORS_ALLOW_ALL_ORIGINS = True  # Apenas para desenvolvimento
CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
INSTALLED_APPS += [
    'django_celery_results',
    'django_celery_beat',
]

CELERY_BROKER_URL = 'sqla+sqlite:///celerydb.sqlite'
CELERY_RESULT_BACKEND = 'django-db'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'





from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'enviar-mensagem-rsu-manha': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_rsu_whatsapp_task',
        'schedule': crontab(minute='30,45,0,15', hour='7-9'),
    },
    'enviar-mensagem-rsu-1030': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_rsu_whatsapp_task',
        'schedule': crontab(hour=10, minute=30),
    },
    'enviar-mensagem-rsu-1130': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_rsu_whatsapp_task',
        'schedule': crontab(hour=11, minute=50),
    },
    'enviar-mensagem-rsu-1250': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_rsu_whatsapp_task',
        'schedule': crontab(hour=12, minute=50),
    },
    'enviar-mensagem-seletiva-1257': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=12, minute=57),
    },
    'enviar-mensagem-rsu-1300': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_rsu_whatsapp_task',
        'schedule': crontab(hour=13, minute=0),
    },
    'enviar-mensagem-seletiva-1300': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=13, minute=7),
    },
    'enviar-mensagem-rsu-1314': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_rsu_whatsapp_task',
        'schedule': crontab(hour=13, minute=14),
    },
     'enviar-mensagem-seletiva-1300': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=13, minute=21),
    },
    'enviar-mensagem-rsu-1600': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_rsu_whatsapp_task',
        'schedule': crontab(hour=16, minute=0),
    },
    'enviar-mensagem-rsu-intervalo-15min': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_rsu_whatsapp_task',
        'schedule': crontab(hour='19-21', minute= '30,45,0,15'),  # RSU roda nos minutos 0 e 30
    },
    'enviar-mensagem-seletiva-600': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=6, minute=45),
    },
    'enviar-mensagem-seletiva-700': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=7, minute=10),
    },
    'enviar-mensagem-seletiva-800': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=8, minute=50),
    },
    'enviar-mensagem-seletiva-1000': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=10, minute=50),
    },
    'enviar-mensagem-seletiva-1100': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=11, minute=50),
    },
    'enviar-mensagem-seletiva-1200': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=12, minute=50),
    },
    # Tarefas para seletiva - sem coincidir com RSU
    'enviar-mensagem-seletiva-1400': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=14, minute=10),
    },
    'enviar-mensagem-seletiva-1600': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=16, minute=10),
    },
    'enviar-mensagem-seletiva-1800': {
        'task': 'apps.general_recourses_wpp.tasks.enviar_mensagem_seletiva_whatsapp_task',
        'schedule': crontab(hour=18, minute=10),
    },
    
}



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ALLOWED_HOSTS = ['192.168.0.233', 'localhost', '127.0.0.1','0.0.0.0','192.168.0.53','192.168.0.76',"192.168.0.112","192.168.0.103",'192.168.0.72','192.168.0.77',]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'  # ou o fuso horário correto da sua aplicação
USE_TZ = True 


USE_I18N = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'