# Generated by Django 5.1.7 on 2025-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=22)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('senha', models.CharField(max_length=7)),
            ],
        ),
    ]
