# Generated by Django 5.1.7 on 2025-03-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.user_mobile')),
            ],
        ),
    ]
