# Generated by Django 5.1.7 on 2025-05-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo_equipamento', models.CharField(max_length=20)),
                ('implemento', models.CharField(choices=[('Retroescavadeira', 'Retroescavadeira'), ('Caminhão Carroceiria', 'Caminhão Carroceiria'), ('Pá Carregadeira', 'Pá Carregadeira')], max_length=20)),
                ('status_equipamento', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7)),
                ('motivo_inatividade', models.CharField(blank=True, choices=[('Em garagem', 'Em garagem'), ('Manutenção', 'Manutenção')], max_length=20, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['prefixo_equipamento'], name='equipamento_prefixo_1c771e_idx'), models.Index(fields=['implemento'], name='equipamento_impleme_b38e8b_idx')],
            },
        ),
    ]
